apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: simplecalc-com-tls
spec:
  secretName: simplecalc-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: simplecalc.com
  dnsNames:
    - simplecalc.com
    - www.simplecalc.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - simplecalc.com
          - www.simplecalc.com
      